#############################################
## OVERRIDE OF hasuraci/centos-base
## Changes:
##  - centos:8 -> centos:stream9 (glibc 2.28 -> 2.34)
##  - Set "dnf config-manager --enable CRB" (Extra Packages repo) to enable mysql libs
##  - Add package for "libmysqlclient.so.21"
#############################################
FROM quay.io/centos/centos:stream9

# Dependencies taken from: https://github.com/0x777/hge-arm-dockerfiles/blob/master/hge.df
# Below are the CentOS libraries matching these apt/Debian ones:
# libpq5 libkrb5-3 libnuma1 ca-certificates (ca-certificates are preinstalled)
RUN dnf -y install 'dnf-command(config-manager)' \
    && dnf config-manager --set-enabled crb \
    && dnf upgrade -y \
    && dnf install -y \
    libpq-13.2-4.el9 \
    krb5-libs \
    numactl-libs \
    libstdc++ \
    compat-openssl11-1:1.1.1k-3.el9

# msodbcsql17
RUN curl https://packages.microsoft.com/config/rhel/8/prod.repo > /etc/yum.repos.d/mssql-release.repo
RUN yum remove unixODBC-utf16 unixODBC-utf16-devel
RUN ACCEPT_EULA=Y yum install -y msodbcsql17 unixODBC-devel

# mysql
RUN dnf install -y mysql-libs mariadb-connector-c-3.1.13-3.el9 \
    && ln -s /usr/lib64/libpcre.so.1 /usr/lib64/libpcre.so.3 

# Node
RUN dnf -y install nodejs

RUN yum clean all && rm -rf /var/cache/yum \
    && dnf clean all && rm -rf /var/cache/dnf

#############################################
WORKDIR /app
COPY ./graphql-engine /usr/bin
COPY ./docker-entrypoint-combined-centos.sh ./

# Node
COPY package.json tsconfig.json /app/
RUN npm install

COPY ./src /app/src
RUN mkdir -p /app/dist
RUN npm run build
RUN npm prune --production

# Get rid of NPM
RUN rm -rf /lib/node_modules/npm /usr/bin/npm

EXPOSE 8080
EXPOSE 3000

RUN ["chmod", "+x", "/app/docker-entrypoint-combined-centos.sh"]
CMD ["bash", "/app/docker-entrypoint-combined-centos.sh"]
